version: "3.9"
services:
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    command: npm run dev
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "3001:3001"